head_camera:
  type: opencv
  video_id: 0
  image_shape:
  - 480
  - 1280
  fps: 30
  enable_zmq: false
  zmq_port: 55555
  enable_webrtc: false
  webrtc_port: 66666
left_wrist_camera:
  type: opencv
  video_id: 2
  image_shape:
  - 480
  - 640
  fps: 30
  enable_zmq: false
  zmq_port: 55556
  enable_webrtc: false
  webrtc_port: 66667
right_wrist_camera:
  type: opencv
  video_id: 4
  image_shape:
  - 480
  - 640
  fps: 30
  enable_zmq: false
  zmq_port: 55557
  enable_webrtc: false
  webrtc_port: 66668
